# Use root/example as user/password credentials
version: '3.1'

services:
  search-server:
    image: bleafman/searchbar
    container_name: search-server
    command: [
        # './wait-for-it.sh',
        # 'mongo:27017',
        # '--timeout=120',
        # '--',
        'npm',
        'run',
        'start',
      ]
    depends_on:
      - es
    ports:
      - 3002:3002
    env_file:
      - .env
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: '0.5'
          memory: 250M
      restart_policy:
        condition: on-failure
    volumes:
      - ./search-banner:/opt/search-banner
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints: [node.role == manager]
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: 'http://es:9200'
    depends_on:
      - es
    ports:
      - 5601:5601
    deploy:
      placement:
        constraints: [node.role == manager]
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    deploy:
      placement:
        constraints: [node.role == manager]
networks:
  search:
volumes:
  esdata:
