# Use root/example as user/password credentials
version: '3.1'

services:
  search-server:
    image: bleafman/searchbar
    container_name: search-server
    command: [
        # './wait-for-it.sh',
        # 'mongo:27017',
        # '--timeout=120',
        # '--',
        'npm',
        'run',
        'start',
      ]
    depends_on:
      - es
    ports:
      - 3002:3002
    env_file:
      - .env
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: '0.2'
          memory: 100M
      restart_policy:
        condition: on-failure
    volumes:
      - ./search-banner:/opt/search-banner
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - sdc-esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.0
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: 'http://es:9200'
    depends_on:
      - es
    ports:
      - 5601:5601
  # mongo:
  #   image: mongo
  #   container_name: mongo
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - $HOME/docker/volumes/mongodb:/data/db
volumes:
  sdc-esdata:
    external: true
networks:
  search:
